apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{ parameters.agentName }}
  description: watsonx Orchestrate agent created via Backstage
spec:
  type: service
  owner: {{ parameters.owner }}
  lifecycle: experimental